apiVersion: v1
kind: Service
metadata:
  name: telecom-middleware
  labels:
    app: telecom-middleware
spec:
  type: ClusterIP
  selector:
    app: telecom-middleware
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: http
